<Project>

  <PropertyGroup>
    <!-- ── Authorship ───────────────────────────────────────────────────── -->
    <Authors>Oscar Fernandez Gonzalez a.k.a. Osc@rNET and Contributors</Authors>
    <Company>OscarNET-SOFTware</Company>
    <Copyright>Copyright (c) 2026 Oscar Fernandez Gonzalez a.k.a. Osc@rNET and Contributors</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Product>Retro.TUI.Framework</Product>

    <!-- ── Versioning ───────────────────────────────────────────────────── -->
    <!-- VersionSuffix is cleared on stable releases.                        -->
    <!-- Result: $(VersionPrefix)-$(VersionSuffix) → 0.1.0-alpha.1           -->
    <VersionPrefix>0.4.0</VersionPrefix>
    <VersionSuffix>alpha.4</VersionSuffix>

    <!-- ── Build options ────────────────────────────────────────────────── -->
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
