<Project>

  <!-- Import root Directory.Build.props -->
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"
          Condition="'' != $([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"/>

  <PropertyGroup>
    <!-- ── Build options ────────────────────────────────────────────────── -->
    <Configurations>Debug;Release</Configurations>
    <DebugSymbols>true</DebugSymbols>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>

    <!-- ── Output options ───────────────────────────────────────────────── -->
    <OutputType Condition="'$(OS)' == 'Windows_NT'">WinExe</OutputType>
    <OutputType Condition="'$(OS)' != 'Windows_NT'">Exe</OutputType>

    <!-- ── Packaging options ────────────────────────────────────────────── -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <!-- ── Debug configuration ────────────────────────────────────────────── -->
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DebugType>portable</DebugType>
    <DefineConstants>TRACE;DEBUG</DefineConstants>
  </PropertyGroup>

  <!-- ── Release configuration ──────────────────────────────────────────── -->
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>embedded</DebugType>
    <DefineConstants>TRACE;RELEASE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

</Project>
