// ---------------------------------------------------------------------------------------------------------------------
// <copyright file="TuiFocusEvent.cs" company="OscarNET-SOFTware">
// ···
//      Retro.TUI.Framework - A modern C-Sharp .NET multiplatform TUI framework
//      powered by SkiaSharp, inspired by Turbo Vision with a PC Tools 9.x retro aesthetic.
// ···
//      Copyright (c) 2026 Oscar Fernandez Gonzalez a.k.a. Osc@rNET and Contributors
//      Licensed under the MIT License. See the 'LICENSE.md' file for details.
// ···
//      Third-party components are used in this project. For full license texts,
//      see the 'licenses' folder and the 'THIRD-PARTY-NOTICES.md' file.
// ···
// </copyright>
// ---------------------------------------------------------------------------------------------------------------------

namespace Retro.TUI.Events;

/// <summary>
/// Represents a keyboard-focus change event dispatched to a view when it gains or loses focus.
/// </summary>
/// <param name="Action">
/// <see cref="TuiFocusAction.Gained"/> when the view receives focus,
/// or <see cref="TuiFocusAction.Lost"/> when focus moves away from it.
/// </param>
/// <remarks>
/// Focus events are generated by the message loop in response to Tab navigation,
/// mouse clicks on focusable views, or programmatic focus changes via the view tree.
/// </remarks>
public sealed record TuiFocusEvent(
    TuiFocusAction Action
) : TuiEvent;
